INSERT INTO area(name_of_area) VALUES('Будённовский');
INSERT INTO area(name_of_area) VALUES('Ворошиловский');
INSERT INTO area(name_of_area) VALUES('Калининский');
INSERT INTO area(name_of_area) VALUES('Киевский');
INSERT INTO area(name_of_area) VALUES('Кировский');
INSERT INTO area(name_of_area) VALUES('Куйбышевский');
INSERT INTO area(name_of_area) VALUES('Ленинский');
INSERT INTO area(name_of_area) VALUES('Петровский');
INSERT INTO area(name_of_area) VALUES('Пролетарский')