INSERT INTO pharmacy_name(name) VALUES('Живы-Здоровы');
INSERT INTO pharmacy_name(name) VALUES('СБЕР ЕАПТЕКА');
INSERT INTO pharmacy_name(name) VALUES('La Roche-Posay');
INSERT INTO pharmacy_name(name) VALUES('Будь здоров!');
INSERT INTO pharmacy_name(name) VALUES('Ригла');
INSERT INTO pharmacy_name(name) VALUES('Столетник');
INSERT INTO pharmacy_name(name) VALUES('Аптека-Эконом');
INSERT INTO pharmacy_name(name) VALUES('Реал Фарма');
INSERT INTO pharmacy_name(name) VALUES('Надежда-Фарм');
INSERT INTO pharmacy_name(name) VALUES('ДЕЖУРНАЯ АПТЕКА');
INSERT INTO pharmacy_name(name) VALUES('Аптека от склада');
INSERT INTO pharmacy_name(name) VALUES('Планета Фарма');
INSERT INTO pharmacy_name(name) VALUES('Кит-фарма');
INSERT INTO pharmacy_name(name) VALUES('Столички');
INSERT INTO pharmacy_name(name) VALUES('ЗдравСити');
INSERT INTO pharmacy_name(name) VALUES('Аптека24');
INSERT INTO pharmacy_name(name) VALUES('Доктор Н');
INSERT INTO pharmacy_name(name) VALUES('Планета здоровья');
INSERT INTO pharmacy_name(name) VALUES('ГОРЗДРАВ');
INSERT INTO pharmacy_name(name) VALUES('ФМБА России');
INSERT INTO pharmacy_name(name) VALUES('ФОРТЕ');
INSERT INTO pharmacy_name(name) VALUES('36,6');
INSERT INTO pharmacy_name(name) VALUES('АСНА');
INSERT INTO pharmacy_name(name) VALUES('Самсон-Фарма');
INSERT INTO pharmacy_name(name) VALUES('Симплекс')