INSERT INTO pharmacological_group(pharmacological_group) VALUES('Адренолитические препараты');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Органотропные препараты');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Оксазолидиноны');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Антиагреганты');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Анаболики');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Анксиолитики');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Анилиды');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Вазодилататоры');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Глюкокортикостероиды');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Гастропротекторы');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Регенеранты и репаранты');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Дофаминомиметики');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Симпатолитики');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Желудочно-кишечные препараты');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Инсулины');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Иммунодепрессанты');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Интерлейкины');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Индукторы интерферонов');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Сульфаниламиды');
INSERT INTO pharmacological_group(pharmacological_group) VALUES('Тетрациклины')